# Pytorch tensor basics

In [1]:
import torch
import numpy as np

## Creating tensors

A tensor is any n-dimensional array.

### Dimensions of tensors

Creating tensors of various dimensions using torch.tensor() function.

In [117]:
# 1D Tensor

t1 = torch.tensor(3.)
print(t1)
print(t1.shape)
print(t1.dtype)

tensor(3.)
torch.Size([])
torch.float32


For one item, the value can be shown as a scalor using ```item()``` function.

In [118]:
print(t1.item())

3.0


In [119]:
# 2D Tensor

t2 = torch.tensor([1,2.,3, 4, 5, 6])
print(t2)
print(t2.shape)
print(t2.dtype)

tensor([1., 2., 3., 4., 5., 6.])
torch.Size([6])
torch.float32


In [120]:
# 3D Tensor

t3 = torch.tensor([[1,2,3],[4,5,6]])
print(t3)
print(t3.shape)
print(t3.dtype)

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])
torch.int64


## Tensor Functions and Operations

### Creating tensors with zeros, ones and fixed values

In [5]:
print(torch.zeros(2, 3), '\n')
print(torch.ones(2, 3), '\n')
print(torch.full((2, 3), 10))

tensor([[0., 0., 0.],
        [0., 0., 0.]]) 

tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

tensor([[10, 10, 10],
        [10, 10, 10]])


### Creating tensor with random values

In [6]:
# Random numbers from uniform distribution on the interval [0,1]

print(torch.rand(1),'\n')
print(torch.rand(2, 3),'\n')

# Random numbers from normal distribution with mean 0 and variance 1

print(torch.randn(3, 5))

tensor([0.3729]) 

tensor([[0.8203, 0.8353, 0.5866],
        [0.9852, 0.0410, 0.8238]]) 

tensor([[-0.7363,  0.0690,  0.2766,  0.4313, -1.1196],
        [-0.1675,  0.1817,  0.2527,  0.6426,  0.6983],
        [-0.7148,  1.3318, -0.6159,  0.2004, -0.8732]])


### Reshaping tensors

Reshaping can be done using ```view()```, ```reshape()``` (both of these take the new dimensions as parameters) or ```permute()``` (this takes the new arrangement of dimensions as parameters).

In [111]:
t4 = torch.tensor([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(t4,'\n')

# Rearranging dimensions
print(t4.permute(0, 1),'\n')

# Reshaping dimensions using .view
print(t4.reshape(2, 2, 3), '\n')

# Reshaping dimensions using .reshape
print(t4.reshape(2, 2, 3))

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]) 

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]) 

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]]) 

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])


### Transposing

In [8]:
print(t4,'\n')
print(t4.t())

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]) 

tensor([[ 1,  4,  7, 10],
        [ 2,  5,  8, 11],
        [ 3,  6,  9, 12]])


### Mathematical Functions

In [15]:
print(t4)
print(torch.sum(t4))
print(torch.sum(t4,dim = 0))
print(torch.sum(t4,dim = 1))

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])
tensor(78)
tensor([22, 26, 30])
tensor([ 6, 15, 24, 33])


Arithmetic operations using ```add_()``` function, which adds a value to all values in the tensor.

In [121]:
print(t3, '\n')
t3.add_(10)
print(t3, '\n')

tensor([[1, 2, 3],
        [4, 5, 6]]) 

tensor([[11, 12, 13],
        [14, 15, 16]]) 



In [35]:
# Central Tendencies

x = torch.tensor([1, 3, 5, 7, 7], dtype = torch.float64)
print(x, '\n')
print(torch.mean(x))
print(torch.median(x))
print(torch.mode(x))

tensor([1., 3., 5., 7., 7.], dtype=torch.float64) 

tensor(4.6000, dtype=torch.float64)
tensor(5., dtype=torch.float64)
torch.return_types.mode(
values=tensor(7., dtype=torch.float64),
indices=tensor(4))


In [36]:
# Trigonometric

print(torch.sin(t4),'\n')
print(torch.cos(t4))

tensor([[ 0.8415,  0.9093,  0.1411],
        [-0.7568, -0.9589, -0.2794],
        [ 0.6570,  0.9894,  0.4121],
        [-0.5440, -1.0000, -0.5366]]) 

tensor([[ 0.5403, -0.4161, -0.9900],
        [-0.6536,  0.2837,  0.9602],
        [ 0.7539, -0.1455, -0.9111],
        [-0.8391,  0.0044,  0.8439]])


### Concatenation

In [37]:
t5=torch.tensor([[1,2,3],[4,5,6]])
t6=torch.tensor([[7,8,9],[10,11.,12]])

print(torch.cat((t5,t6),axis=0),'\n')
print(torch.cat((t5,t6),axis=1))

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]]) 

tensor([[ 1.,  2.,  3.,  7.,  8.,  9.],
        [ 4.,  5.,  6., 10., 11., 12.]])


### Arithmetic operations

In [116]:
t2.add_(0)

tensor([10., 11., 12., 13., 14., 15.])

In [38]:
t7 = torch.tensor(2)
t8 = torch.tensor(3)

print(t7+t8)
print(t8/t7)

tensor(5)
tensor(1.5000)


Element-wise multiplication:

In [40]:
t9 = torch.tensor([[1,2],[0,1]])
t10 = torch.tensor([[0,10],[1,0]])

print(t9 * t10)

tensor([[ 0, 20],
        [ 0,  0]])


Matrix Multiplication:

In [41]:
print(t9 @ t10)

tensor([[ 2, 10],
        [ 1,  0]])


## Gradients using Autograd

Useful for finding derivative of a variable wrt other.

### Initiating tensors with gradients

For the variables wrt which we'll need derivatives, we pass parameter ```requires_grad=True```.

In [124]:
x = torch.tensor(3)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True,)

print(x,w,b)

tensor(3) tensor(4., requires_grad=True) tensor(5., requires_grad=True)


In [125]:
y = w * x 
print(y)
y = w * x + b
print(y)

tensor(12., grad_fn=<MulBackward0>)
tensor(17., grad_fn=<AddBackward0>)


Detach the gradient requirement:

In [126]:
print(y.detach())

tensor(17.)


### Computing derivative using autograd

Using ```backward()``` function to calculate derivatives using Vector-Jacobian product system. To find the derivate wrt a variable, we check the variable's ```grad``` parameter.

To do autograd multiple times, use ```y.backward(retain_graph=True)```.

In [127]:
y.backward()

print('dy/dx:', x.grad)
print('dy/dw:', w.grad)
print('dy/db:', b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


Resetting gradients to zero 

In [128]:
w.grad.zero_()
b.grad.zero_()

print('dy/dw:', w.grad)
print('dy/db:', b.grad)

dy/dw: tensor(0.)
dy/db: tensor(0.)


## Interoperability with Numpy

Changing tensors from numpy object to pytorch.tensor objects, and vice versa.

### Numpy to tensor

In [21]:
x = np.array([[1,2,3],[4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
y = torch.from_numpy(x)
y

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

### Tensor to Numpy

In [23]:
z = y.numpy()
z

array([[1, 2, 3],
       [4, 5, 6]])