# Pytorch tensor basics

In [3]:
import torch
import numpy as np

## Creating tensors

A tensor is any n-dimensional array.

Creating tensors of various dimensions using torch.tensor() function.

### 1D Tensor

In [4]:
t1 = torch.tensor(3.)
print(t1)
print(t1.shape)
print(t1.dtype)

tensor(3.)
torch.Size([])
torch.float32


### 2D Tensor

In [5]:
t2 = torch.tensor([1,2.,3])
print(t2)
print(t2.shape)
print(t2.dtype)

tensor([1., 2., 3.])
torch.Size([3])
torch.float32


### 3D Tensor

In [6]:
t3 = torch.tensor([[1,2,3],[4,5,6]])
print(t3)
print(t3.shape)
print(t3.dtype)

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])
torch.int64


## Tensor Functions and Operations

### Creating tensor with fixed value

In [7]:
print(torch.full((2, 3), 10))

tensor([[10, 10, 10],
        [10, 10, 10]])


### Creating tensor with random values

In [22]:
# Random numbers from uniform distribution on the interval [0,1]

print(torch.rand(1),'\n')
print(torch.rand(2, 3),'\n')

# Random numbers from normal distribution with mean 0 and variance 1

print(torch.randn(3, 5))

tensor([0.6857]) 

tensor([[0.9835, 0.9113, 0.7237],
        [0.0823, 0.6671, 0.7900]]) 

tensor([[-0.0765,  1.2477,  1.1166, -0.5138,  1.2141],
        [ 1.4848,  0.4836,  1.1753, -0.3474,  0.4662],
        [-2.2896,  1.4040, -0.1094, -0.5667,  0.5293]])


### Reshaping tensors

In [173]:
t4 = torch.tensor([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(t4,'\n')
print(t4.reshape(2,2,3))

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]) 

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])


### Transposing

In [174]:
print(t4,'\n')
print(t4.t())

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]) 

tensor([[ 1,  4,  7, 10],
        [ 2,  5,  8, 11],
        [ 3,  6,  9, 12]])


### Mathematical Functions

In [175]:
print(torch.sum(t4))
print(torch.sum(t4,axis=0))
print(torch.sum(t4,axis=1))

tensor(78)
tensor([22, 26, 30])
tensor([ 6, 15, 24, 33])


In [176]:
print(torch.sin(t4),'\n')
print(torch.cos(t4))

tensor([[ 0.8415,  0.9093,  0.1411],
        [-0.7568, -0.9589, -0.2794],
        [ 0.6570,  0.9894,  0.4121],
        [-0.5440, -1.0000, -0.5366]]) 

tensor([[ 0.5403, -0.4161, -0.9900],
        [-0.6536,  0.2837,  0.9602],
        [ 0.7539, -0.1455, -0.9111],
        [-0.8391,  0.0044,  0.8439]])


### Concatenation

In [177]:
t5=torch.tensor([[1,2,3],[4,5,6]])
t6=torch.tensor([[7,8,9],[10,11.,12]])

print(torch.cat((t5,t6),axis=0),'\n')
print(torch.cat((t5,t6),axis=1))

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]]) 

tensor([[ 1.,  2.,  3.,  7.,  8.,  9.],
        [ 4.,  5.,  6., 10., 11., 12.]])


### Arithmetic operations

In [178]:
t7 = torch.tensor(2)
t8 = torch.tensor(3)

print(t7+t8)
print(t8/t7)

tensor(5)
tensor(1.5000)


### Element wise multiplication

In [179]:
t9 = torch.tensor([[1,2],[0,1]])
t10 = torch.tensor([[0,10],[1,0]])

print(t9 * t10)

tensor([[ 0, 20],
        [ 0,  0]])


### Matrix Multiplication

In [180]:
print(t9 @ t10)

tensor([[ 2, 10],
        [ 1,  0]])


## Gradients

Useful for finding derivative of a variable wrt other.

### Initiating tensors with gradients

For the variables wrt which we'll need derivatives, we pass parameter ```requires_grad=True```.

In [38]:
x = torch.tensor(3)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True,)

print(x,w,b)

tensor(3) tensor(4., requires_grad=True) tensor(5., requires_grad=True)


In [39]:
y=w*x+b
print(y)

tensor(17., grad_fn=<AddBackward0>)


### Computing derivative using autograd

Using ```backward()``` function to calculate derivatives. To find the derivate wrt a variable, we check the variable's ```grad``` parameter.

To do autograd multiple times, use ```y.backward(retain_graph=True)```.

In [40]:
y.backward()

print('dy/dx:', x.grad)
print('dy/dw:', w.grad)
print('dy/db:', b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


### Resetting gradients to zero 

In [41]:
w.grad.zero_()
b.grad.zero_()

print('dy/dw:', w.grad)
print('dy/db:', b.grad)

dy/dw: tensor(0.)
dy/db: tensor(0.)


## Interoperability with Numpy

Changing tensors from numpy object to pytorch.tensor objects, and vice versa.

### Numpy to tensor

In [185]:
x = np.array([[1,2,3],[4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [186]:
y = torch.from_numpy(x)
y

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

### Tensor to Numpy

In [119]:
z = y.numpy()
z

array([[1, 2, 3],
       [4, 5, 6]])